In [1]:
import yfinance as yf

In [9]:
btc = yf.Ticker("BTC-USD")

In [10]:
btc

yfinance.Ticker object <BTC-USD>

In [11]:
btc.info

{'companyOfficers': [],
 'name': 'Bitcoin',
 'startDate': 1367107200,
 'description': 'Bitcoin (BTC) is a cryptocurrency . Users are able to generate BTC through the process of mining. Bitcoin has a current supply of 19,078,025. The last known price of Bitcoin is 21,062.9603148 USD and is down -1.53 over the last 24 hours. It is currently trading on 9584 active market(s) with $18,685,698,527.70 traded over the last 24 hours. More information can be found at https://bitcoin.org/.',
 'maxAge': 1,
 'exchange': 'CCC',
 'shortName': 'Bitcoin USD',
 'exchangeTimezoneName': 'UTC',
 'exchangeTimezoneShortName': 'UTC',
 'isEsgPopulated': False,
 'gmtOffSetMilliseconds': '0',
 'quoteType': 'CRYPTOCURRENCY',
 'symbol': 'BTC-USD',
 'messageBoardId': 'finmb_BTC_CCC',
 'market': 'ccc_market',
 'previousClose': 21024.48,
 'regularMarketOpen': 21024.48,
 'twoHundredDayAverage': 38514.645,
 'trailingAnnualDividendYield': None,
 'payoutRatio': None,
 'volume24Hr': 22046724096,
 'regularMarketDayHigh': 21466.805,
 'navPrice': None,
 'averageDailyVolume10Day': 28038085702,
 'totalAssets': None,
 'regularMarketPreviousClose': 21024.48,
 'fiftyDayAverage': 27418.594,
 'trailingAnnualDividendRate': None,
 'open': 21024.48,
 'toCurrency': 'USD=X',
 'averageVolume10days': 28038085702,
 'expireDate': None,
 'yield': None,
 'algorithm': None,
 'dividendRate': None,
 'exDividendDate': None,
 'beta': None,
 'circulatingSupply': 19078506,
 'regularMarketDayLow': 20686.123,
 'priceHint': 2,
 'currency': 'USD',
 'regularMarketVolume': 22046724096,
 'lastMarket': 'CoinMarketCap',
 'maxSupply': None,
 'openInterest': None,
 'marketCap': 395724029952,
 'volumeAllCurrencies': 22046724096,
 'strikePrice': None,
 'averageVolume': 31846129132,
 'priceToSalesTrailing12Months': None,
 'dayLow': 20686.123,
 'ask': None,
 'ytdReturn': None,
 'askSize': None,
 'volume': 22046724096,
 'fiftyTwoWeekHigh': 68789.625,
 'forwardPE': None,
 'fromCurrency': 'BTC',
 'fiveYearAvgDividendYield': None,
 'fiftyTwoWeekLow': 17708.623,
 'bid': None,
 'tradeable': False,
 'dividendYield': None,
 'bidSize': None,
 'dayHigh': 21466.805,
 'regularMarketPrice': 20741.879,
 'preMarketPrice': None,
 'logo_url': ''}

In [13]:
btc_candle = btc.history()

In [15]:
type(btc_candle)

pandas.core.frame.DataFrame

In [17]:
btc_candle.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2022-05-27,29251.140625,29346.943359,28326.613281,28627.574219,36582005748,0,0
2022-05-28,28622.625000,28814.900391,28554.566406,28814.900391,35519577634,0,0
2022-05-29,29019.867188,29498.009766,28841.107422,29445.957031,18093886409,0,0
2022-05-30,29443.365234,31949.630859,29303.572266,31726.390625,39277993274,0,0
2022-05-31,31723.865234,32249.863281,31286.154297,31792.310547,33538210634,0,0

In [19]:
btc_candle.tail(3)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2022-06-25,21233.609375,21520.914062,20964.585938,21502.337891,18372538715,0,0
2022-06-26,21496.494141,21783.724609,21016.269531,21027.294922,18027170497,0,0
2022-06-27,21024.480469,21466.804688,20686.123047,20728.134766,22023026688,0,0

In [38]:
btcCV = btc_candle[["Close","Volume"]].copy()
btcCV.head(2)

                   Close       Volume
Date
2022-05-27  28627.574219  36582005748
2022-05-28  28814.900391  35519577634

In [24]:
btcCV.shape

(32, 2)

In [43]:
btcCV["change"] = (btcCV.Close - btcCV.Close.shift(1))
btcCV["change%"] = round(100*(btcCV.Close - btcCV.Close.shift(1))/btcCV.Close.shift(1),2)

btcCV

                   Close       Volume       change  change%
Date
2022-05-27  28627.574219  36582005748          NaN      NaN
2022-05-28  28814.900391  35519577634   187.326172     0.65
2022-05-29  29445.957031  18093886409   631.056641     2.19
2022-05-30  31726.390625  39277993274  2280.433594     7.74
2022-05-31  31792.310547  33538210634    65.919922     0.21
2022-06-01  29799.080078  41135817341 -1993.230469    -6.27
2022-06-02  30467.488281  29083562061   668.408203     2.24
2022-06-03  29704.390625  26175547452  -763.097656    -2.50
2022-06-04  29832.914062  16588370958   128.523438     0.43
2022-06-05  29906.662109  17264085441    73.748047     0.25
2022-06-06  31370.671875  31947336829  1464.009766     4.90
2022-06-07  31155.478516  40770974039  -215.193359    -0.69
2022-06-08  30214.355469  30242059107  -941.123047    -3.02
2022-06-09  30111.998047  21692004719  -102.357422    -0.34
2022-06-10  29083.804688  29867476527 -1028.193359    -3.41
2022-06-11  28360.810547  27246574439  -722.994141    -2.49
2022-06-12  26762.648438  34163220274 -1598.162109    -5.64
2022-06-13  22487.388672  68204556440 -4275.259766   -15.97
2022-06-14  22206.792969  50913575242  -280.595703    -1.25
2022-06-15  22572.839844  54912007015   366.046875     1.65
2022-06-16  20381.650391  31183975654 -2191.189453    -9.71
2022-06-17  20471.482422  27132421514    89.832031     0.44
2022-06-18  19017.642578  42009436760 -1453.839844    -7.10
2022-06-19  20553.271484  35329942625  1535.628906     8.07
2022-06-20  20599.537109  30818458597    46.265625     0.23
2022-06-21  20710.597656  28970212744   111.060547     0.54
2022-06-22  19987.029297  28574793478  -723.568359    -3.49
2022-06-23  21085.876953  26188097173  1098.847656     5.50
2022-06-24  21231.656250  24957784918   145.779297     0.69
2022-06-25  21502.337891  18372538715   270.681641     1.27
2022-06-26  21027.294922  18027170497  -475.042969    -2.21
2022-06-27  20728.134766  22023026688  -299.160156    -1.42